services:
  backend_service:
    build: ./backend
    container_name: backend-container
    restart: always
    env_file: 
      - ./backend/.env
    ports: 
      - "3000:3000"


  frontend_service:
    build: ./frontend
    container_name: frontend-container
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "4000:4000"
    depends_on:
      - backend_service